# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [ ]:
'''
Your Code
'''

'\nYour Code\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [1]:
# 記得先 Import 正確的套件

import numpy as np


'\nimport numpy as np\n'

In [33]:
import numpy as np

a = np.random.randint(10, size=6) 


print('陣列維度：',a.ndim)
print('陣列大小：',a.shape)
print('陣列尺寸：',a.size)
print('資料類別：',a.dtype)
print('元素佔用空間：',a.itemsize)



#一個數字=一行幾個

陣列維度： 1
陣列大小： (6,)
陣列尺寸： 6
資料類別： int64
元素佔用空間： 8


AttributeError: 'numpy.ndarray' object has no attribute 'length'

In [35]:
b = np.random.randint(10, size=(3,4)) 

print('陣列維度：',b.ndim)
print('陣列大小：',b.shape)
print('陣列尺寸：',b.size)
print('資料類別：',b.dtype)
print('元素佔用空間：',b.itemsize)

#2個數字=行＊列

陣列維度： 2
陣列大小： (3, 4)
陣列尺寸： 12
資料類別： int64
元素佔用空間： 8


In [36]:
c = np.random.randint(10, size=(2,3,2)) 

print('陣列維度：',c.ndim)
print('陣列大小：',c.shape)
print('陣列尺寸：',c.size)
print('資料類別：',c.dtype)
print('元素佔用空間：',c.itemsize)

#3個數字=個數＊行＊列

陣列維度： 3
陣列大小： (2, 3, 2)
陣列尺寸： 12
資料類別： int64
元素佔用空間： 8


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [38]:
def tolist(iterable):

    iterable=np.random.randint(10, size=(2,3))
    return iterable

print(tolist(a))
print(tolist(b))
print(tolist(c))

[[4 1 4]
 [6 0 3]]
[[4 7 2]
 [3 0 3]]
[[6 1 8]
 [3 2 8]]


In [44]:
print(list(a))
print(b.tolist())
print(c.tolist())


[1, 9, 7, 5, 2, 6]
[[4, 7, 0, 3], [1, 6, 5, 2], [5, 8, 4, 6]]
[[[1, 1], [9, 2], [5, 5]], [[3, 4], [5, 0], [2, 9]]]
