In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [10]:
a[1:20]
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [20]:
array=np.arange(20)
array[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
array=np.arange(20)
array[3:20:3]



array([ 3,  6,  9, 12, 15, 18])

In [5]:
print('ndim: ', a.ndim)



NameError: name 'a' is not defined